In [145]:
import pandas
from pandas import read_csv
import numpy
from keras.models import Sequential
from keras.layers import Dense

In [147]:
dataframe = pandas.read_csv("Desktop/Datasets/test1.csv")
dataset = dataframe.values

In [149]:
x = dataset[:,1:21]

In [151]:
y = dataset[:,21]

In [152]:
y

array([1, 4, 3, 2, 3, 2, 2, 2, 0, 2, 2, 3, 2, 0, 2, 2, 3, 4, 1, 2, 3, 2, 4,
       2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 2, 2, 3, 3, 4, 2, 2, 2, 2, 2, 3, 0, 4,
       0, 0, 1, 2, 2, 2, 2, 0, 3, 3, 3, 2, 2, 4, 2, 3, 3, 2, 3, 2, 2, 2, 2,
       2, 3, 3, 3, 2, 1, 4, 3, 3, 2, 2, 2, 2, 4, 0, 2, 2, 2, 3, 0, 4, 1, 3,
       2, 3, 0, 3, 4, 0, 2])

In [153]:
model = Sequential()
model.add(Dense(20, input_dim=20, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [154]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dataset[:,1:21], dataset[:,21], test_size=0.25, random_state=87)

In [155]:
model.fit(x_train,y_train,nb_epoch =100, batch_size =16,verbose =2)

Epoch 1/100
 - 3s - loss: 6.7579 - acc: 0.1216
Epoch 2/100
 - 0s - loss: 6.1066 - acc: 0.1216
Epoch 3/100
 - 0s - loss: 5.3640 - acc: 0.1216
Epoch 4/100
 - 0s - loss: 4.7528 - acc: 0.1216
Epoch 5/100
 - 0s - loss: 4.1617 - acc: 0.1216
Epoch 6/100
 - 0s - loss: 3.5829 - acc: 0.1216
Epoch 7/100
 - 0s - loss: 3.0480 - acc: 0.1216
Epoch 8/100
 - 0s - loss: 2.5829 - acc: 0.1216
Epoch 9/100
 - 0s - loss: 2.1705 - acc: 0.1486
Epoch 10/100
 - 0s - loss: 1.7458 - acc: 0.1757
Epoch 11/100
 - 0s - loss: 1.4181 - acc: 0.2162
Epoch 12/100
 - 0s - loss: 1.1295 - acc: 0.2703
Epoch 13/100
 - 0s - loss: 0.8863 - acc: 0.3919
Epoch 14/100
 - 0s - loss: 0.6732 - acc: 0.4459
Epoch 15/100
 - 0s - loss: 0.5264 - acc: 0.4865
Epoch 16/100
 - 0s - loss: 0.4088 - acc: 0.6216
Epoch 17/100
 - 0s - loss: 0.3263 - acc: 0.6892
Epoch 18/100
 - 0s - loss: 0.2690 - acc: 0.7027
Epoch 19/100
 - 0s - loss: 0.2335 - acc: 0.7027
Epoch 20/100
 - 0s - loss: 0.2087 - acc: 0.7162
Epoch 21/100
 - 0s - loss: 0.1987 - acc: 0.7703
E

In [157]:
prediction = model.predict(x).astype('int')

In [158]:
prediction

array([[1],
       [4],
       [3],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [2],
       [2],
       [1],
       [0],
       [1],
       [2],
       [2],
       [4],
       [1],
       [2],
       [2],
       [2],
       [4],
       [2],
       [2],
       [3],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [3],
       [2],
       [4],
       [2],
       [2],
       [1],
       [1],
       [2],
       [3],
       [0],
       [4],
       [0],
       [0],
       [0],
       [1],
       [2],
       [2],
       [1],
       [0],
       [3],
       [2],
       [2],
       [2],
       [1],
       [4],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [3],
       [1],
       [0],
       [4],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [4],
    

In [159]:
import pandas as pd 
pred_1 = pd.DataFrame(prediction)

In [160]:
pred_1

0
0   1
1   4
2   3
3   1
4   2
5   2
6   1
7   1
8   0
9   1
10  2
11  2
12  1
13  0
14  1
15  2
16  2
17  4
18  1
19  2
20  2
21  2
22  4
23  2
24  2
25  3
26  1
27  2
28  2
29  1
.. ..
69  2
70  2
71  2
72  3
73  1
74  0
75  4
76  2
77  2
78  2
79  2
80  1
81  1
82  4
83  0
84  2
85  1
86  2
87  2
88  0
89  4
90  1
91  2
92  2
93  2
94  0
95  2
96  4
97  0
98  2

[99 rows x 1 columns]

In [126]:
pred_100 = model.predict(x)


In [127]:
pred_100[20]

array([ 1.6027627], dtype=float32)

In [128]:
prediction = model.predict(x).astype('int')

In [129]:
prediction


array([[2],
       [0],
       [2],
       [2],
       [0],
       [1],
       [2],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [0],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [0],
       [2],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [0],
       [1],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [0],
       [2],
       [1],
       [0],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [3],
    

In [110]:
import pandas as pd 
pred_1 = pd.DataFrame(prediction)

In [111]:
pred_1

0
0   1
1   4
2   3
3   2
4   2
5   2
6   1
7   1
8   0
9   1
10  2
11  3
12  2
13  0
14  1
15  2
16  2
17  4
18  0
19  2
20  3
21  1
22  4
23  2
24  1
25  3
26  1
27  1
28  3
29  2
.. ..
69  1
70  2
71  1
72  3
73  2
74  1
75  4
76  2
77  2
78  2
79  2
80  1
81  1
82  4
83  0
84  2
85  1
86  2
87  2
88  0
89  4
90  0
91  1
92  2
93  2
94  0
95  2
96  4
97  0
98  1

[99 rows x 1 columns]

In [161]:
prediction.to_csv("Desktop/Datasets/Churn_Modelling.csv")

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

In [164]:
prediction = pd.read_csv("Desktop/Datasets/Churn_Modelling.csv")

In [165]:
prediction

Unnamed: 0  0
0            0  1
1            1  4
2            2  3
3            3  2
4            4  2
5            5  2
6            6  1
7            7  1
8            8  0
9            9  1
10          10  2
11          11  3
12          12  2
13          13  0
14          14  1
15          15  2
16          16  2
17          17  4
18          18  0
19          19  2
20          20  3
21          21  1
22          22  4
23          23  2
24          24  1
25          25  3
26          26  1
27          27  1
28          28  3
29          29  2
..         ... ..
69          69  1
70          70  2
71          71  1
72          72  3
73          73  2
74          74  1
75          75  4
76          76  2
77          77  2
78          78  2
79          79  2
80          80  1
81          81  1
82          82  4
83          83  0
84          84  2
85          85  1
86          86  2
87          87  2
88          88  0
89          89  4
90          90  0
91          91  1
92          92  2
93          93  2
94          94  0
95          95  2
96          96  4
97          97  0
98          98  1

[99 rows x 2 columns]

In [114]:
df_5

Unnamed: 0  0
0            0  1
1            1  4
2            2  3
3            3  2
4            4  2
5            5  2
6            6  1
7            7  1
8            8  0
9            9  1
10          10  2
11          11  3
12          12  2
13          13  0
14          14  1
15          15  2
16          16  2
17          17  4
18          18  0
19          19  2
20          20  3
21          21  1
22          22  4
23          23  2
24          24  1
25          25  3
26          26  1
27          27  1
28          28  3
29          29  2
..         ... ..
69          69  1
70          70  2
71          71  1
72          72  3
73          73  2
74          74  1
75          75  4
76          76  2
77          77  2
78          78  2
79          79  2
80          80  1
81          81  1
82          82  4
83          83  0
84          84  2
85          85  1
86          86  2
87          87  2
88          88  0
89          89  4
90          90  0
91          91  1
92          92  2
93          93  2
94          94  0
95          95  2
96          96  4
97          97  0
98          98  1

[99 rows x 2 columns]

In [137]:
df_5[1,:]

TypeError: unhashable type

In [134]:
fd = open('test2.csv','a')
fd.write(df_5[0,1])
fd.close()

KeyError: (0, 1)